### ISSUE TITLE
Network Errors in Server Console

### ISSUE THREAD

**Issue by A248** [CraftingStore/MinecraftPlugin#3]
**Plugin Version**
2.2.1

**Server Version**
git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Issue Description**
`Exception`s are infrequently, although annoyingly, printed in full to the server console. I make my best attempts to keep the console clean so that I can focus on the important messages. It is frustrating to scroll past network timeout and response code exceptions.
SocketTimeoutException: https://pastebin.com/2E8ZyvDz
HttpResponseException: https://pastebin.com/ApdS9Jzf

**Extra Background**
I have just recently started using CraftingStore. Your services are much appreciated. As I'm still in the process of moving packages from my old store hosting service, there have been no purchases on the new site yet. This may be a potential reason behind the messages:
- "Caused by: net.craftingstore.core.exceptions.CraftingStoreApiException: Donation Queue call failed".
- "Caused by: net.craftingstore.core.exceptions.CraftingStoreApiException: Payments call failed"

**Comment by Tim-NL** [comment]
Hello,

How often do these come up? It might indicate a network issue on your, or our side. 

-Tim

**Comment by A248** [comment]
It first happened at 10 AM UTC-5 on 20 February 2020. The issue arises irregularly and infrequently, on average every 18 hours.

My machine's firewall is configured to accept all outgoing connections. Also, it does not rate-limit incoming connections. Does the CraftingStore Plugin listen on any ports? If so, I will need to whitelist them.

**Comment by Tim-NL** [comment]
Our plugin does not listen on any ports, but it does create a web socket connection. We have made some changes, so the error message should not show again, could you update this issue if you see it appear again?

-Tim

**Comment by A248** [comment]
Sorry, it appears the bug returned at 3:47 today (UTC-5). It seems the issue is a connection timeout, as it reads: `java.net.SocketTimeoutException: Read timed out`. The cause is listed as `java.util.concurrent.ExecutionException: net.craftingstore.core.exceptions.CraftingStoreApiException: Donation Queue call failed`. The full report is the same stacktrace in the first pastebin link I provided above.

**Comment by Tim-NL** [comment]
Did it come up since then? We received a large DDoS attack (too large to handle without external mitigation), causing some of our services to go offline for a small moment, it took about 30 seconds for our DDoS protection provider to kick in and mitigate the attack, and 50 seconds for our failover system to move the server that was being attacked outside of the active pool, so other servers can start to take over requests.

-Tim

**Comment by A248** [comment]
Yes, I received 2 more stacktraces at around 5 AM yesterday (28 February, UTC-5). The same `java.net.SocketTimeoutException: Read timed out` as well as another `java.net.UnknownHostException: api.craftingstore.net: Name or service not known`.

**Comment by A248** [comment]
CraftingStore recently threw another error I haven't seen before, another `HttpResponseException`, but with cause description `Inventory call failed`.
https://pastebin.com/EN8qG0Zf

**Comment by x0Z3ro0x** [comment]
Hello. Joining in on the discussion because I have a similar print out to the console, that I believe to be relevant to this issue.

Here is my printoff -

https://pastebin.com/EjMyX6N7

**Comment by Tim-NL** [comment]
OVH, one of the providers we use to host some of our servers has issues at the moment (https://ovh.com/ is also not reachable from here). 

Our fallback system noticed, and moved all of our infrastructures over to Germany instead. SO there might have been some missed API calls during the detection time and the actual move (should not have been more than ~2 minutes).

**Comment by x0Z3ro0x** [comment]
I hope everything is going ok. Getting the read time outs several times today. Please let me know if there is anything I can do to help.

**Comment by M4tZeSS** [comment]
Hello, I am also having this issue for weeks now. Error log is down below.

```
[SEVERE] java.net.SocketTimeoutException: Read timed out
[SEVERE] at java.net.SocketInputStream.socketRead0(Native Method)
[SEVERE] at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[SEVERE] at java.net.SocketInputStream.read(SocketInputStream.java:171)
[SEVERE] at java.net.SocketInputStream.read(SocketInputStream.java:141)
[SEVERE] at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
[SEVERE] at sun.security.ssl.InputRecord.read(InputRecord.java:503)
[SEVERE] at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
[SEVERE] at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
[SEVERE] at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
[SEVERE] at net.craftingstore.libraries.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
[SEVERE] at net.craftingstore.libraries.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
[SEVERE] at net.craftingstore.libraries.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
[SEVERE] at net.craftingstore.core.http.CraftingStoreAPIImpl.lambda$getGUI$8(CraftingStoreAPIImpl.java:135)
[SEVERE] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SEVERE] at java.lang.Thread.run(Thread.java:748)
[SEVERE] java.util.concurrent.ExecutionException: net.craftingstore.core.exceptions.CraftingStoreApiException: Inventory call failed
[SEVERE] at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[SEVERE] at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[SEVERE] at net.craftingstore.core.http.CraftingStoreCachedAPI.refreshGUICache(CraftingStoreCachedAPI.java:55)
[SEVERE] at net.craftingstore.core.scheduler.InventoryRenewer.run(InventoryRenewer.java:28)
[SEVERE] at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[SEVERE] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[SEVERE] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[SEVERE] at java.lang.Thread.run(Thread.java:748)
[SEVERE] Caused by: net.craftingstore.core.exceptions.CraftingStoreApiException: Inventory call failed
[SEVERE] at net.craftingstore.core.http.CraftingStoreAPIImpl.lambda$getGUI$8(CraftingStoreAPIImpl.java:137)
[SEVERE] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[SEVERE] ... 3 more
```

I am running a waterfall fork as server software.

If any other information is needed to fix this issue, I'd be glad to help.

Thanks,
-Mathis

**Comment by Tim-NL** [comment]
During the OVH downtime, when one of our dedicated servers and a few VM's fell down, our other location took over. But it could not cope with the sheer amount of requests that our API is getting hit by (all servers that fetch commands/inventory/info/top buyers/recent buyers) from our API every so often. 

The issue is not related to limitations in our hardware, but more in the configuration. Our load balancers and Varnish cache servers could handle everything just fine (with 0% CPU usage in fact) but our web servers did throw "400 bad requests" out. While still using at most 1% of their CPU. 

The server was set to start a maximum of 30 workers to handle the requests, and that's not enough. It required at least 110 workers to handle the normal traffic on its own (in normal situations the load would be shared through many physical locations and servers, so it would hardly be a problem).

Today we pointed all load again towards our location in Germany and modified the configuration of our web servers and load balancers. Now the servers can handle all requests (and spikes) without any problems, CPU usage almost never reaches 3% and we have more than enough headroom for extra traffic.

Also, our Varnish caching proxies try to take away a lot of unnecessary load by caching responses that didn't change over time, there is no need in fetching the recent buyers from the database if it never changed.

Over the last ~1.000.000 requests sent, about 5 failed with a 400 bad request-response, with no errors in our logs, or workers. 

We are now confident that all locations can handle the full load of our platform in case there is a major outage. 

That's why there were some "read timeouts" in the last few days. Let us know if they return!

**Comment by x0Z3ro0x** [comment]
Wow, very impressive job handling the situation. I am glad everything worked out in the end! Thank you for keeping in touch with us!
