### ISSUE TITLE
Package price is an integer

### ISSUE THREAD

**Issue by 04fsnape** [CraftingStore/MinecraftPlugin#5]
Hello,

The price variable is stored as an integer, and hence any packages with a float price such as £3.50 are rounded to £4.00 when using the DonationReceivedEvent.

I think you should store price as a BigDecimal.

I'm not sure exactly where you should implement this fix, as it's possible that it will break people's code in the unlikely event that they are set to use the latest version of the live API. So maybe create a new branch.

Thanks.

**Comment by 04fsnape** [comment]
I was thinking that perhaps you could add an optional boolean parameter to `.getPrice()`, where if you set it to true it returns the price in pence as an integer. I think this is actually preferable to BigDecimal, and doesn't break anyone's code.

**Comment by thijsa** [comment]
Thank you for bringing this issue to our attention. We have fixed this issue in version 2.4.0, which will be released soon. You can view the commit here: https://github.com/CraftingStore/MinecraftPlugin/commit/86bbbc8d19e66cc4bc2907eb212530f41a41c633.

I have deprecated the `.getPrice()` method and added a `.getPriceFloat()` method to the `DonationPackage` class in order to preserve backwards compatibility. 

You can now also retrieve the payment/donation the command is part of with the `.getPaymentId()` method.

**Comment by 04fsnape** [comment]
@thijsa thank you. I noticed you have a function that gets the package price in cents, but it is not exposed in the DonationReceivedEvent? I think it would be much better actually to use that instead of the price as a float. If you'd rather use a float-esque data type then may I suggest changing to BigDecimal?

https://javarevisited.blogspot.com/2012/02/java-mistake-1-using-float-and-double.html

**Comment by thijsa** [comment]
Thank you, the plugin will now use BigDecimal to store the package price. The method is now called `getPriceDecimal()`.

I will not expose the price in cents for the time being, because this is only used internally in the API and don't want plugins to rely on this data. You can calculate the cents yourself with the `getPriceDecimal()` method.

**Comment by 04fsnape** [comment]
@thijsa thanks. probably simpler to use `BigDecimal price = BigDecimal.valueOf(apiDonation.getPackagePriceCent / 100d);`

however, using cents in general is much more stable and so it would be extremely preferable if you could allow access to a method that will return the cents. i.e. remove the `/ 100f` from the function call, and instead do that just for `getPriceDecimal()`, using the line above.

you may also want to considering switching `int` to `BigInteger` for cents.

**Comment by thijsa** [comment]
The `valueOf` method of BigDecimal does exactly the same internally using `Double.toString()`, and using floats over doubles has no real advantage as we only use two decimals places by dividing by 100.

I see no real advantage for exposing the actual cents in the plugin API, as plugin developers will rarely need to use the actual cents over the decimal value. 

There will never be a payment that is over the 32 bit limit for the integer type, so I see no reason to store the price in BigInteger.

**Comment by 04fsnape** [comment]
@thijsa I know it's the same, just good to have clear and concise code. `valueOf` is the preferred way of converting.

I am storing the prices in cents, it is definitely preferable to decimal and much less prone to issues. Please add least add this as an additional method, on top of `getPriceDecimal()`, which can take this value `/100`.

That's true, I suppose it's just standard.
